name: CI
on:
    pull_request:
    push:
        branches: [ main ]

jobs:
    tests:
        name: Unit Tests
        runs-on: ubuntu-latest
        timeout-minutes: 30
        concurrency:
            group: "tests-${{ github.ref }}"
            cancel-in-progress: true
        steps:
            -   uses: actions/checkout@v4
            -   name: Setup Java JDK
                uses: actions/setup-java@v4.2.1
                with:
                    java-version: 21
                    distribution: adopt
            -   name: "Setup gradle"
                uses: gradle/actions/setup-gradle@v3.3.2
            -   name: "Gradle Command - test"
                run: ./gradlew clean test
            -   name: "Upload Test Logs Artifact"
                uses: actions/upload-artifact@v4
                if: failure()
                with:
                    name: unit-test-logs
                    path: build/reports/tests/
            -   name: Add coverage to PR
                uses: madrapps/jacoco-report@v1.6.1
                if: github.event_name == 'pull_request' && github.actor != 'dependabot[bot]'
                with:
                    paths: ${{ github.workspace }}/build/reports/jacoco/test/jacocoTestReport.xml
                    token: ${{ secrets.GITHUB_TOKEN }}
                    min-coverage-overall: 90
                    title: "Jacoco Coverage Report"
                    update-comment: true

    owasp:
        name: "OWASP check"
        runs-on: ubuntu-latest
        timeout-minutes: 30
        concurrency:
            group: "owasp-check-${{ github.ref }}"
            cancel-in-progress: true
        steps:
            -   name: "Checkout Code"
                uses: actions/checkout@v4
            -   name: "Setup Java JDK"
                uses: actions/setup-java@v4.2.1
                with:
                    java-version: 21
                    distribution: adopt
            -   name: Cache Dependency Database
                uses: actions/cache@v4
                with:
                    path: "~/.gradle/dependency-check-data/"
                    key: "owasp-check"
            -   name: "Setup gradle"
                uses: gradle/actions/setup-gradle@v3.3.2
            -   name: "Execute dependencyCheckUpdate"
                continue-on-error: true
                run: "./gradlew dependencyCheckUpdate"
            -   name: "Execute dependencyCheckAnalyze"
                continue-on-error: true
                run: "./gradlew dependencyCheckAnalyze"
            -   id: "eval"
                name: "Evaluate OWASP report"
                uses: raynigon/gradle-owasp-parser@main
                continue-on-error: true
                with:
                    fail_on_vulnerabilities: "true"
                    path_report: "build/reports/dependency-check-report.json"
                    path_build_gradle: "build.gradle.kts"
            -   name: Add comment to PR
                if: ${{ failure() && github.event_name == 'pull_request' }}
                uses: thollander/actions-comment-pull-request@v2
                with:
                    message: |
                        ${{ steps.eval.outputs.report_markdown }}
                    comment_tag: 'Comment-ID: owasp-report-${{ github.ref }}'
